/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as RetrieveAccountRouteImport } from './routes/retrieve-account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FinanceHubRouteImport } from './routes/finance-hub'
import { Route as FinanceAdvisorRouteImport } from './routes/finance-advisor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfirmDeletionRouteImport } from './routes/confirm-deletion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayUsernameRouteImport } from './routes/pay.$username'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrieveAccountRoute = RetrieveAccountRouteImport.update({
  id: '/retrieve-account',
  path: '/retrieve-account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceHubRoute = FinanceHubRouteImport.update({
  id: '/finance-hub',
  path: '/finance-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAdvisorRoute = FinanceAdvisorRouteImport.update({
  id: '/finance-advisor',
  path: '/finance-advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmDeletionRoute = ConfirmDeletionRouteImport.update({
  id: '/confirm-deletion',
  path: '/confirm-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayUsernameRoute = PayUsernameRouteImport.update({
  id: '/pay/$username',
  path: '/pay/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm-deletion': typeof ConfirmDeletionRoute
  '/dashboard': typeof DashboardRoute
  '/finance-advisor': typeof FinanceAdvisorRoute
  '/finance-hub': typeof FinanceHubRoute
  '/help': typeof HelpRoute
  '/kyc': typeof KycRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/retrieve-account': typeof RetrieveAccountRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/sign-up': typeof SignUpRoute
  '/transactions': typeof TransactionsRoute
  '/pay/$username': typeof PayUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-deletion': typeof ConfirmDeletionRoute
  '/dashboard': typeof DashboardRoute
  '/finance-advisor': typeof FinanceAdvisorRoute
  '/finance-hub': typeof FinanceHubRoute
  '/help': typeof HelpRoute
  '/kyc': typeof KycRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/retrieve-account': typeof RetrieveAccountRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/sign-up': typeof SignUpRoute
  '/transactions': typeof TransactionsRoute
  '/pay/$username': typeof PayUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirm-deletion': typeof ConfirmDeletionRoute
  '/dashboard': typeof DashboardRoute
  '/finance-advisor': typeof FinanceAdvisorRoute
  '/finance-hub': typeof FinanceHubRoute
  '/help': typeof HelpRoute
  '/kyc': typeof KycRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/retrieve-account': typeof RetrieveAccountRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/sign-up': typeof SignUpRoute
  '/transactions': typeof TransactionsRoute
  '/pay/$username': typeof PayUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-deletion'
    | '/dashboard'
    | '/finance-advisor'
    | '/finance-hub'
    | '/help'
    | '/kyc'
    | '/loans'
    | '/login'
    | '/retrieve-account'
    | '/savings'
    | '/settings'
    | '/sign-up'
    | '/transactions'
    | '/pay/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-deletion'
    | '/dashboard'
    | '/finance-advisor'
    | '/finance-hub'
    | '/help'
    | '/kyc'
    | '/loans'
    | '/login'
    | '/retrieve-account'
    | '/savings'
    | '/settings'
    | '/sign-up'
    | '/transactions'
    | '/pay/$username'
  id:
    | '__root__'
    | '/'
    | '/confirm-deletion'
    | '/dashboard'
    | '/finance-advisor'
    | '/finance-hub'
    | '/help'
    | '/kyc'
    | '/loans'
    | '/login'
    | '/retrieve-account'
    | '/savings'
    | '/settings'
    | '/sign-up'
    | '/transactions'
    | '/pay/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmDeletionRoute: typeof ConfirmDeletionRoute
  DashboardRoute: typeof DashboardRoute
  FinanceAdvisorRoute: typeof FinanceAdvisorRoute
  FinanceHubRoute: typeof FinanceHubRoute
  HelpRoute: typeof HelpRoute
  KycRoute: typeof KycRoute
  LoansRoute: typeof LoansRoute
  LoginRoute: typeof LoginRoute
  RetrieveAccountRoute: typeof RetrieveAccountRoute
  SavingsRoute: typeof SavingsRoute
  SettingsRoute: typeof SettingsRoute
  SignUpRoute: typeof SignUpRoute
  TransactionsRoute: typeof TransactionsRoute
  PayUsernameRoute: typeof PayUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrieve-account': {
      id: '/retrieve-account'
      path: '/retrieve-account'
      fullPath: '/retrieve-account'
      preLoaderRoute: typeof RetrieveAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-hub': {
      id: '/finance-hub'
      path: '/finance-hub'
      fullPath: '/finance-hub'
      preLoaderRoute: typeof FinanceHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-advisor': {
      id: '/finance-advisor'
      path: '/finance-advisor'
      fullPath: '/finance-advisor'
      preLoaderRoute: typeof FinanceAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-deletion': {
      id: '/confirm-deletion'
      path: '/confirm-deletion'
      fullPath: '/confirm-deletion'
      preLoaderRoute: typeof ConfirmDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$username': {
      id: '/pay/$username'
      path: '/pay/$username'
      fullPath: '/pay/$username'
      preLoaderRoute: typeof PayUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmDeletionRoute: ConfirmDeletionRoute,
  DashboardRoute: DashboardRoute,
  FinanceAdvisorRoute: FinanceAdvisorRoute,
  FinanceHubRoute: FinanceHubRoute,
  HelpRoute: HelpRoute,
  KycRoute: KycRoute,
  LoansRoute: LoansRoute,
  LoginRoute: LoginRoute,
  RetrieveAccountRoute: RetrieveAccountRoute,
  SavingsRoute: SavingsRoute,
  SettingsRoute: SettingsRoute,
  SignUpRoute: SignUpRoute,
  TransactionsRoute: TransactionsRoute,
  PayUsernameRoute: PayUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
